# DATA PREPROCESSING AND DATA CLEANING

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [21]:
df = pd.read_csv('GENERATION.csv')
df.head()

,Day of Year,Year,Month,Day,First Hour of Period,Is Daylight,Distance to Solar Noon,Average Temperature (Day),Average Wind Direction (Day),Average Wind Speed (Day),Sky Cover,Visibility,Relative Humidity,Average Wind Speed (Period),Average Barometric Pressure (Period),Power Generated
0,245,2008,9,1,1,False,0.859897,69,28,7.5,0,10.0,75,8.0,29.82,0
1,245,2008,9,1,4,False,0.628535,69,28,7.5,0,10.0,77,5.0,29.85,0
2,245,2008,9,1,7,True,0.397172,69,28,7.5,0,10.0,70,0.0,29.89,5418
3,245,2008,9,1,10,True,0.165810,69,28,7.5,0,10.0,33,0.0,29.91,25477
4,245,2008,9,1,13,True,0.065553,69,28,7.5,0,10.0,21,3.0,29.89,30069

In [23]:
df.tail()

,Day of Year,Year,Month,Day,First Hour of Period,Is Daylight,Distance to Solar Noon,Average Temperature (Day),Average Wind Direction (Day),Average Wind Speed (Day),Sky Cover,Visibility,Relative Humidity,Average Wind Speed (Period),Average Barometric Pressure (Period),Power Generated
2915,243,2009,8,31,10,True,0.166453,63,27,13.9,4,10.0,75,10.0,29.93,6995
2916,243,2009,8,31,13,True,0.064020,63,27,13.9,1,10.0,66,15.0,29.91,29490
2917,243,2009,8,31,16,True,0.294494,63,27,13.9,2,10.0,68,21.0,29.88,17257
2918,243,2009,8,31,19,True,0.524968,63,27,13.9,2,10.0,81,17.0,29.87,677
2919,243,2009,8,31,22,False,0.755442,63,27,13.9,1,10.0,81,11.0,29.90,0

In [4]:
df.shape

(2920, 16)

In [5]:
df.size

46720

In [6]:
df.columns

Index(['Day of Year', 'Year', 'Month', 'Day', 'First Hour of Period',
       'Is Daylight', 'Distance to Solar Noon', 'Average Temperature (Day)',
       'Average Wind Direction (Day)', 'Average Wind Speed (Day)', 'Sky Cover',
       'Visibility', 'Relative Humidity', 'Average Wind Speed (Period)',
       'Average Barometric Pressure (Period)', 'Power Generated'],
      dtype='object')

In [7]:
df.isnull()

,Day of Year,Year,Month,Day,First Hour of Period,Is Daylight,Distance to Solar Noon,Average Temperature (Day),Average Wind Direction (Day),Average Wind Speed (Day),Sky Cover,Visibility,Relative Humidity,Average Wind Speed (Period),Average Barometric Pressure (Period),Power Generated
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2916,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2917,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2918,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2919,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df = df.dropna()

In [10]:
df['Power Generated'].unique()

array([    0,  5418, 25477, ...,  6995, 29490, 17257], dtype=int64)

In [11]:
df.describe()

,Day of Year,Year,Month,Day,First Hour of Period,Distance to Solar Noon,Average Temperature (Day),Average Wind Direction (Day),Average Wind Speed (Day),Sky Cover,Visibility,Relative Humidity,Average Wind Speed (Period),Average Barometric Pressure (Period),Power Generated
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000
mean,183.282631,2008.665982,6.524495,15.715999,11.501542,0.503327,58.468996,24.957862,10.099486,1.987667,9.559609,73.505995,10.129154,30.017712,6982.182939
std,105.751253,0.471727,3.448038,8.795825,6.875714,0.298069,6.842318,6.912203,4.837128,1.412220,1.380290,15.073974,7.261547,0.142006,10313.330078
min,1.000000,2008.000000,1.000000,1.000000,1.000000,0.050401,42.000000,1.000000,1.100000,0.000000,0.000000,14.000000,0.000000,29.480000,0.000000
25%,92.000000,2008.000000,4.000000,8.000000,5.500000,0.232061,53.000000,25.000000,6.600000,1.000000,10.000000,65.000000,5.000000,29.920000,0.000000
50%,183.000000,2009.000000,7.000000,16.000000,13.000000,0.479241,59.000000,27.000000,10.000000,2.000000,10.000000,77.000000,9.000000,30.000000,404.000000
75%,275.000000,2009.000000,10.000000,23.000000,17.500000,0.739559,63.000000,29.000000,13.100000,3.000000,10.000000,84.000000,15.000000,30.110000,12725.000000
max,366.000000,2009.000000,12.000000,31.000000,22.000000,1.141361,78.000000,36.000000,26.600000,4.000000,10.000000,100.000000,40.000000,30.530000,36580.000000

In [12]:
df.corr()

,Day of Year,Year,Month,Day,First Hour of Period,Is Daylight,Distance to Solar Noon,Average Temperature (Day),Average Wind Direction (Day),Average Wind Speed (Day),Sky Cover,Visibility,Relative Humidity,Average Wind Speed (Period),Average Barometric Pressure (Period),Power Generated
Day of Year,1.000000,-0.818412,0.996520,0.094129,0.000320,-0.055288,0.044453,0.257789,0.192094,-0.088287,-0.052670,-0.004226,0.031508,-0.073227,-0.122886,-0.037070
Year,-0.818412,1.000000,-0.818255,-0.001974,-0.000317,0.087559,-0.135724,-0.046688,0.005246,0.304131,0.092584,0.089275,-0.003405,0.214389,-0.069480,0.122813
Month,0.996520,-0.818255,1.000000,0.011230,0.000291,-0.055260,0.043132,0.263076,0.186718,-0.081456,-0.048429,-0.004915,0.028697,-0.068733,-0.128667,-0.036304
Day,0.094129,-0.001974,0.011230,1.000000,0.000339,0.004517,-0.000434,-0.021992,0.111685,-0.035234,-0.050991,0.027752,0.031739,-0.023474,0.037990,0.007063
First Hour of Period,0.000320,-0.000317,0.000291,0.000339,1.000000,0.173255,-0.062237,-0.000048,-0.000420,-0.000338,-0.073585,0.049903,-0.251581,0.289482,-0.033481,0.107209
Is Daylight,-0.055288,0.087559,-0.055260,0.004517,0.173255,1.000000,-0.827087,0.067295,0.056829,0.060376,0.028588,-0.086235,-0.341510,0.192290,-0.054039,0.532336
Distance to Solar Noon,0.044453,-0.135724,0.043132,-0.000434,-0.062237,-0.827087,1.000000,-0.145235,-0.118293,-0.145301,-0.015183,0.065541,0.369278,-0.214891,0.082633,-0.746825
Average Temperature (Day),0.257789,-0.046688,0.263076,-0.021992,-0.000048,0.067295,-0.145235,1.000000,0.342216,0.096194,-0.230673,0.194354,-0.221440,0.054546,-0.435728,0.132155
Average Wind Direction (Day),0.192094,0.005246,0.186718,0.111685,-0.000420,0.056829,-0.118293,0.342216,1.000000,0.340899,-0.137217,0.201546,-0.095053,0.229844,-0.271973,0.146463
Average Wind Speed (Day),-0.088287,0.304131,-0.081456,-0.035234,-0.000338,0.060376,-0.145301,0.096194,0.340899,1.000000,0.107840,0.183281,0.005676,0.673626,-0.379447,0.142366
Sky Cover,-0.052670,0.092584,-0.048429,-0.050991,-0.073585,0.028588,-0.015183,-0.230673,-0.137217,0.107840,1.000000,-0.224131,0.394722,0.044301,-0.091531,-0.187248
Visibility,-0.004226,0.089275,-0.004915,0.027752,0.049903,-0.086235,0.065541,0.194354,0.201546,0.183281,-0.224131,1.000000,-0.290180,0.143621,-0.104273,0.075841
Relative Humidity,0.031508,-0.003405,0.028697,0.031739,-0.251581,-0.341510,0.369278,-0.221440,-0.095053,0.005676,0.394722,-0.290180,1.000000,-0.218042,0.017987,-0.522445
Average Wind Speed (Period),-0.073227,0.214389,-0.068733,-0.023474,0.289482,0.192290,-0.214891,0.054546,0.229844,0.673626,0.044301,0.143621,-0.218042,1.000000,-0.293457,0.278174
Average Barometric Pressure (Period),-0.122886,-0.069480,-0.128667,0.037990,-0.033481,-0.054039,0.082633,-0.435728,-0.271973,-0.379447,-0.091531,-0.104273,0.017987,-0.293457,1.000000,-0.036553
Power Generated,-0.037070,0.122813,-0.036304,0.007063,0.107209,0.532336,-0.746825,0.132155,0.146463,0.142366,-0.187248,0.075841,-0.522445,0.278174,-0.036553,1.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 2919
Data columns (total 16 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Day of Year                           2919 non-null   int64
 1   Year                                  2919 non-null   int64
 2   Month                                 2919 non-null   int64
 3   Day                                   2919 non-null   int64
 4   First Hour of Period                  2919 non-null   int64
 5   Is Daylight                           2919 non-null   bool
 6   Distance to Solar Noon                2919 non-null   float64
 7   Average Temperature (Day)             2919 non-null   int64
 8   Average Wind Direction (Day)          2919 non-null   int64
 9   Average Wind Speed (Day)              2919 non-null   float64
 10  Sky Cover                             2919 non-null   int64
 11  Visibility                            2919 non-null   float64
 12  Relative Humidity                     2919 non-null   int64
 13  Average Wind Speed (Period)           2919 non-null   float64
 14  Average Barometric Pressure (Period)  2919 non-null   float64
 15  Power Generated                       2919 non-null   int64
dtypes: bool(1), float64(5), int64(10)
memory usage: 367.7 KB

In [15]:
pd.crosstab(df["Relative Humidity"], df["Power Generated"])

Power Generated,0,1,2,3,6,9,11,12,13,15,...,35405,35474,35486,35553,35635,35743,35778,36368,36400,36580
Relative Humidity,,,,,,,,,,,,,,,,,,,,,
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,38,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
90,127,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93,112,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,46,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
100,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df.groupby(["Visibility","Average Wind Speed (Period)"]).groups

{(0.0, 0.0): [746], (0.25, 0.0): [1042], (0.25, 3.0): [730], (0.25, 5.0): [970, 2882], (0.5, 0.0): [969], (0.5, 3.0): [971], (0.75, 6.0): [963], (1.25, 8.0): [973], (1.5, 0.0): [1012, 1156], (1.5, 3.0): [747, 984], (1.5, 5.0): [1013], (1.5, 22.0): [1460], (1.75, 6.0): [1834], (1.75, 9.0): [985], (2.0, 0.0): [459], (2.0, 6.0): [1041], (2.5, 0.0): [779], (2.5, 3.0): [972], (2.5, 5.0): [1035], (2.5, 9.0): [1146], (3.0, 0.0): [1157, 1251], (3.0, 3.0): [451], (3.0, 6.0): [675, 987], (3.0, 7.0): [731], (3.0, 10.0): [1394], (3.0, 13.0): [263, 1397], (3.0, 14.0): [1942], (3.0, 15.0): [491, 493], (3.0, 17.0): [1458], (3.0, 21.0): [509], (4.0, 0.0): [692, 819, 837, 983, 1145, 1147, 1158, 1252], (4.0, 3.0): [722, 1034, 1154, 1242], (4.0, 5.0): [676, 713, 979, 982, 1025], (4.0, 6.0): [450, 729, 778, 1033, 1243], (4.0, 7.0): [1148, 1395, 1396, 1562], (4.0, 8.0): [1115], (4.0, 9.0): [732, 850], (4.0, 10.0): [894, 986], (4.0, 11.0): [1325, 1425], (4.0, 13.0): [1954], (4.0, 14.0): [490, 1342, 1346, 1353], (4.0, 15.0): [492], (4.0, 16.0): [1341], (4.0, 21.0): [2042], (4.0, 22.0): [1338], (5.0, 0.0): [745, 1028, 1219, 1241], (5.0, 3.0): [674, 803, 964, 1026, 1027, 1116, 1153], (5.0, 5.0): [748, 1244], (5.0, 6.0): [777, 1575], (5.0, 7.0): [755, 1032, 1043, 1343], (5.0, 8.0): [1160], (5.0, 9.0): [962, 978], (5.0, 10.0): [893], (5.0, 13.0): [754], (5.0, 14.0): [988, 1985], (5.0, 16.0): [550], (5.0, 20.0): [1339], (5.0, 21.0): [1321], (6.0, 0.0): [613, 693, 725, 728, 813, 980, 1014, 1029, 1107, 1109, 1117, 1155, 1253], (6.0, 3.0): [618, 619, 749, 818, 956], (6.0, 5.0): [723, 955, 961, 1040, 1250, 1561], (6.0, 6.0): [482, 685, 762, 763], (6.0, 7.0): [634], (6.0, 8.0): [1108], (6.0, 9.0): [1569], (6.0, 10.0): [549, 802, 1163, 1408], (6.0, 11.0): [733, 780], (6.0, 13.0): [630], (6.0, 14.0): [1407], (6.0, 17.0): [446], (6.0, 25.0): [923], (6.0, 28.0): [2046], (7.0, 0.0): [449, 474, 475, 617, 684, 772, 1587], (7.0, 3.0): [291, 467, 620, 677, 709, 1969], (7.0, 5.0): [115, 1220, 1835], (7.0, 6.0): [632, 756, 981], (7.0, 7.0): [114, 683, 968, 1152], (7.0, 8.0): [477, 715, 738, 1031], (7.0, 9.0): [466], (7.0, 10.0): [1266, 1309], (7.0, 11.0): [631], (7.0, 13.0): [1941], (7.0, 15.0): [1271], (7.0, 17.0): [265, 452, 1984], (8.0, 0.0): [434, 616, 663, 682, 695, 711, 712, 757, 811, 1039, 1110, 1111, 1113, 1149, 1211, 1586, 2730], (8.0, 3.0): [82, 611, 721, 773, 804, 1212], (8.0, 5.0): [468, 633, 635, 643, 744, 758, 1024, 1114, 1144, 1588, 2731], (8.0, 6.0): [576, 698, 724, 776, 892, 913, 1018, 1019, 1112, 1963, 2338], (8.0, 7.0): [667, 699, 771, 1159], (8.0, 8.0): [266, 612, 816, 1968], (8.0, 9.0): [441, 1347, 2002], (8.0, 10.0): [1320], (8.0, 11.0): [1215, 1459, 1467, 2118], (8.0, 13.0): [2578], (8.0, 14.0): [1602, 2110, 2126, 2259], (8.0, 15.0): [447, 921], (8.0, 16.0): [1406], (8.0, 18.0): [2117, 2413], (8.0, 24.0): [1337], (8.0, 25.0): [1402], ...}

In [18]:
df["Power Generated"].value_counts()

0        1320
3           3
229         3
738         3
30          2
         ...
8581        1
12545       1
52          1
8277        1
17257       1
Name: Power Generated, Length: 1528, dtype: int64

In [19]:
pd.Categorical(df["Average Temperature (Day)"]).describe()

            counts     freqs
categories
42               8  0.002741
43              24  0.008222
44               8  0.002741
45              16  0.005481
46              24  0.008222
47              56  0.019185
48              56  0.019185
49             128  0.043851
50              80  0.027407
51              96  0.032888
52             120  0.041110
53             120  0.041110
54             136  0.046591
55             184  0.063035
56             136  0.046591
57             127  0.043508
58              88  0.030147
59             160  0.054813
60             128  0.043851
61             168  0.057554
62             240  0.082220
63             152  0.052073
64             152  0.052073
65             104  0.035629
66             112  0.038369
67              48  0.016444
68              40  0.013703
69              48  0.016444
70              32  0.010963
71              32  0.010963
72               8  0.002741
73              24  0.008222
74              24  0.008222
75              16  0.005481
76               8  0.002741
77               8  0.002741
78               8  0.002741

In [24]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2915    False
2916    False
2917    False
2918    False
2919    False
Length: 2920, dtype: bool

In [26]:
sum(df.duplicated())

0